### ISSUE TITLE
not working when not running at root path

### ISSUE THREAD

**Issue by beyourmarket** [beyourmarket/beyourmarket#10]
working on iis express,
but working well on IIS
at first i have to install the URL Rewrite to make it work
my site work start at http://mydomain/Test
all css and javascripts are broken...

**Comment by beyourmarket** [comment]
fixed now

**Comment by eyeseecute** [comment]
thanks for fixing that, i've download the latest one and try to install the application again, but it shows
"The resource cannot be found. "

**Comment by beyourmarket** [comment]
what exactly are the resources from "the resource cannot be found", do you have more details of what it's missing? thanks.

**Comment by eyeseecute** [comment]
no installation had been done, but the instance somehow treat it as something installed
you may have a look
http://124.244.217.24/BeYourMarket/

**Comment by eyeseecute** [comment]
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)

Line 116:            // Latest
Line 117:            if (items == null)
Line 118:                items = await _itemService.Query().OrderBy(x => x.OrderByDescending(y => y.Created)).Include(x => x.ItemPictures).Include(x => x.Category).SelectAsync();
Line 119:
Line 120:            // Location

Source File: c:\Users\Administrator\Downloads\beyourmarket-master (1)\beyourmarket-master\BeYourMarket.Web\Controllers\HomeController.cs    Line: 118

[SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)]
   System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) +6749670
   System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) +815
   System.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, Boolean encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean withFailover) +6775368
   System.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover) +219
   System.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout) +6777796
   System.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance) +6778255
   System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData) +878
   System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions) +816
   System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions) +72
   System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection) +6781425
   System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection) +103
   System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection) +2105
   System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen() +351
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
   System.Data.Entity.SqlServer.<<ExecuteAsync>b__3>d__6.MoveNext() +459
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
   System.Data.Entity.SqlServer.<ExecuteAsyncImplementation>d__9`1.MoveNext() +709
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
   System.Data.Entity.Core.EntityClient.<OpenAsync>d__8.MoveNext() +950

[EntityException: The underlying provider failed on Open.]
   System.Data.Entity.Core.EntityClient.<OpenAsync>d__8.MoveNext() +1289
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
   System.Data.Entity.Utilities.CultureAwaiter.GetResult() +60
   System.Data.Entity.Core.Objects.<EnsureConnectionAsync>d__9.MoveNext() +698
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
   System.Data.Entity.Core.Objects.<ExecuteInTransactionAsync>d__3d`1.MoveNext() +491
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
   System.Data.Entity.SqlServer.<ExecuteAsyncImplementation>d__9`1.MoveNext() +764
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
   System.Data.Entity.Core.Objects.<GetResultsAsync>d__e.MoveNext() +965
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
   System.Data.Entity.Internal.<FirstMoveNextAsync>d__0.MoveNext() +438
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
   System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() +49
   System.Data.Entity.Utilities.CultureAwaiter`1.GetResult() +60
   System.Data.Entity.Infrastructure.<ForEachAsync>d__5`1.MoveNext() +515
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
   System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() +49
   Repository.Pattern.Ef6.<SelectAsync>d__f.MoveNext() in c:\Users\Administrator\Downloads\beyourmarket-master (1)\beyourmarket-master\Frameworks\Repository.Pattern.Ef6\Repository.cs:196
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
   System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() +49
   Repository.Pattern.Ef6.<SelectAsync>d__0.MoveNext() in c:\Users\Administrator\Downloads\beyourmarket-master (1)\beyourmarket-master\Frameworks\Repository.Pattern.Ef6\QueryFluent.cs:54
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
   System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() +49
   BeYourMarket.Web.Controllers.<GetSearchResult>d__25.MoveNext() in c:\Users\Administrator\Downloads\beyourmarket-master (1)\beyourmarket-master\BeYourMarket.Web\Controllers\HomeController.cs:118
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
   BeYourMarket.Web.Controllers.<Index>d__0.MoveNext() in c:\Users\Administrator\Downloads\beyourmarket-master (1)\beyourmarket-master\BeYourMarket.Web\Controllers\HomeController.cs:47
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
   System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult) +143
   System.Web.Mvc.Async.<>c__DisplayClass37.<BeginInvokeAsynchronousActionMethod>b__36(IAsyncResult asyncResult) +23
   System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +112
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +452
   System.Web.Mvc.Async.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult) +15
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +37
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +241
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +29
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +111
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +53
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +19
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +51
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +111
   System.Web.CallHandlerExecutionStep.OnAsyncHandlerCompletion(IAsyncResult ar) +282

**Comment by beyourmarket** [comment]
okay, it seems the ConnectionString has been set, you shall remove it as
first time.

if you go to connectionstrings.config, paste the following text and save.

<connectionStrings>
</connectionStrings>

Try and see if it launches the installation wizard.

/Ken

**Comment by eyeseecute** [comment]
no , the connectionstrings is empty

**Comment by beyourmarket** [comment]
I think the reason is because you have installed another website on
wwwroot, and using the same connectionString name as "DefaultConnection"

In that case, you need to put the following lines in
connectionstrings.config

<connectionStrings>
  <remove name="DefaultConnection"/>
</connectionStrings>

**Comment by eyeseecute** [comment]
oh yes, it's working fine now !
thanks so much !

**Comment by beyourmarket** [comment]
great and you are welcome. I also check in changes with the web.config and
connectionstring.config. In case others might have the same problem.

**Comment by mis0033** [comment]
hello everybody,

when I uploaded my site (built using Beyourmarket CMS) to Godaddy shared hosting, I got this error, please help , any suggestions ? the web site is http://www.global-energyco.com/en

Server Error in '/globalenergy' Application.

The virtual path '/' maps to another application, which is not allowed.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.ArgumentException: The virtual path '/' maps to another application, which is not allowed.

Please advise , it's URGENT
