### ISSUE TITLE
Main image not displaying on certain devices

### ISSUE THREAD

**Issue by kennethmundt** [beyourmarket/beyourmarket#12]
On my Ipad mini the main image is not displaying in neither Safari or Chrome. Instead there is just a gray area with the slogan and search bar. It's the same on my Samsung Galaxy S2 and its build-in browser

**Comment by beyourmarket** [comment]
do you mean the front page background image? I tried in Chrome on ipad, and it's working. and do you have a link?

**Comment by kennethmundt** [comment]
Yes, the frontpage background image.  

Screenshot attached and link here: www.shareprint.dk

Med venlig hilsen

Kenneth Mundt

**Comment by beyourmarket** [comment]
it's fixed now.
