### ISSUE TITLE
Sub-categories

### ISSUE THREAD

**Issue by kennethmundt** [beyourmarket/beyourmarket#13]
It would be very useful if we can make sub-categories.

**Comment by beyourmarket** [comment]
you can indeed do that, just need to drag the category under another category
![subcategory](https://cloud.githubusercontent.com/assets/12659713/8505375/f74f2e08-21e3-11e5-81bb-614640f83648.JPG)

**Comment by kennethmundt** [comment]
Yes, I tried that. That is, in the Chrome browser. After seeing your response I also tried in Firefox and IE, and it works as intended. However, I cannot do it in Google Chrome browser.

/Kenneth

From: BeYourMarket
Sent: ‎Saturday‎, ‎July‎ ‎4‎, ‎2015 ‎12‎:‎31‎ ‎AM
To: beyourmarket/beyourmarket
Cc: DAT14V1 Kenneth Caleb Mundt

you can indeed do that, just need to drag the category under another category
 subcategory

**Comment by beyourmarket** [comment]
did you get an error or you cannot drag? I made a fix last night regarding the categories, it didn't get refresh until the website restarted. Might be you could also get the latest version.

**Comment by kennethmundt** [comment]
I was unable to drag the category box. It marks the text instead.

From: BeYourMarket
Sent: ‎Saturday‎, ‎July‎ ‎4‎, ‎2015 ‎12‎:‎21‎ ‎PM
To: beyourmarket/beyourmarket
Cc: DAT14V1 Kenneth Caleb Mundt

did you get an error or you cannot drag? I made a fix last night regarding the categories, it didn't get refresh until the website restarted. Might be you could also get the latest version.
