### ISSUE TITLE
Language issue in controller

### ISSUE THREAD

**Issue by net4u** [beyourmarket/beyourmarket#14]
Hi,

with the current build, I have:
A public action method 'LanguageSelector' was not found on controller 'BeYourMarket.Web.Areas.Admin.Controllers.ListingController'.

I have to go, no, but I will check.

**Comment by beyourmarket** [comment]
seems you didn't get all the latest files, please try to get the latest files and rebuild solution.

**Comment by net4u** [comment]
I am on latest files, and is a persistent issue. (Maybe relevant I have in local folder, subfolders for fr and ro languages and are made at a previous release, I just keep them)

**Comment by beyourmarket** [comment]
it shouldn't relate to the locale folder, could you try a fresh installation with the latest files on a separate folder?

**Comment by net4u** [comment]
Is that I done. I clear all in my existing folder, I delete the DB and I proceed to a new install.

**Comment by beyourmarket** [comment]
you are right. I found the bug and it's fixed now. It's in the latest version. Thanks.
