### ISSUE TITLE
Suggestion.

### ISSUE THREAD

**Issue by scharada** [beyourmarket/beyourmarket#15]
a category should have one or more parent categories (more then 1 parent  makes cross referencing listings very easy)...
the same for listings. one listing could belong to one or more categories.

**Comment by beyourmarket** [comment]
do you have a marketplaces where you have items with different parents? because normally each item should only belong to one parent, and the parent could belong to another parent (subcategories which is supported.)

**Comment by beyourmarket** [comment]
it will be closed for now, if there is a strong need later, we would consider to change it.
