### ISSUE TITLE
Null reference on new listing

### ISSUE THREAD

**Issue by marksarcade** [beyourmarket/beyourmarket#16]
Hey, firstly great site!

I've been playing around with it, and keep hitting a null reference error when creating new listings. I tried putting a simple "!= null statement" around the problem in question, that gets rid of the problem but I get no attached files now.

Screenshot below, if it doesn't show the details enough the error is on the line "foreach (HttpPostedFileBase file in files)" in ListingController

![nullreference](https://cloud.githubusercontent.com/assets/2818799/9170814/8b8aac54-3fa9-11e5-89a3-91a68b228cb0.png)

**Comment by beyourmarket** [comment]
Thanks for reporting. I just made a fix, seems it could be related to the multiple attribute. Could you try get the latest version? And please let me know which browser do you use if it's still not working? Thanks.

**Comment by marksarcade** [comment]
That's fixed the image upload problem. I'm still getting the above error on creating a new listing in IE11. I'm NOT getting the error in Firefox 38.0.5. Debugging the two, IEnumerable<HttpPostedFileBase> files is passed in as null in IE11 but as an array with 1 member in Firefox?

**Comment by beyourmarket** [comment]
i get the error in IE11 too, I updated the fileupload js component and I tested it fixed the issues.

**Comment by marksarcade** [comment]
Yep looks good, thanks :)
