### ISSUE TITLE
Paypal plugin

### ISSUE THREAD

**Issue by kangoobeagle** [beyourmarket/beyourmarket#19]
Hello
I saw your documentation that explains how to add a plugin.
Can you please tell me how to add the paypal plugin and where can I find it please ?
Thank you

**Comment by beyourmarket** [comment]
Hi, what kind of Paypal api are you thinking about? is it like Paypal Express api for marketplace?

There is already a Plugin Stripe, one way is you could follow what it's code and you could make the similar one for Paypal. We are planning to build different plugins for different marketplaces api, we could look at it for the paypal too.

**Comment by kangoobeagle** [comment]
Thanks for your answer ! Yes I would like that the buyers and sellers pay and earn money with paypal. Actually, I don't know anything about the code's language I am really lost I only know the Html/css and a little bit of php and that's it. It would be really awesome if you build this plugin and others :+1:

**Comment by kenyeung128** [comment]
yes, we will probably develop a plugin with Braintree api which supports Paypal. Might I ask what kind of marketplace you are building? perhaps we can help you with the customization. Please send email to hello@beyourmarket.com
