### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by net4u** [beyourmarket/beyourmarket#2]
Hi,

I found that in IE and Mozilla, the price tag on upper left corner of image on main view listing is not visible. But it works well in Chrome, Opera and Microsoft Edge. I will investigate tomorrow to figure what can be the cause.
I noticed that in Firefox and IE the respective span is slides much to right: it falls between his image and the next right image. 
I also noticed that when you are in Admin mode in Custom Field -> Add and then you hit Cancel an server error it occurs. Have no more detail at this stage, I will try to investigate more.
 L.E.
 At first sight it seems to be a route related issue:
 you are in http://localhost:53216/en/admin/listing/customfieldupdate and if want to cancel it falls into (not found): http://localhost:53216/en/admin/manage/customfields
 L.E. 2
 It seems that is not (yet) possible to delete (any kind of) entries added?

**Comment by beyourmarket** [comment]
Thanks. I have fixed:
1. Custom field cancel issue.
2. Delete listing issue

**Comment by beyourmarket** [comment]
Fixed

**Comment by net4u** [comment]
The price is still visible only in Chrome and Microsoft Edge. Not in IE and Mozilla
