### ISSUE TITLE
Move to Aspnet.vnext

### ISSUE THREAD

**Issue by rmarinho** [beyourmarket/beyourmarket#20]
With ASPNET 5 and all the new stuff to run CoreCRL cross platform i think it would be a very good bet to move the project in that direction. Also EF will support things like table storage making a very cool candidate to bet on too.

**Comment by beyourmarket** [comment]
it's a very good suggestion and we are also considering that. However, there are 2 concerns we have.
1. Stability of vNext, if there would be lots of breaking changes from Microsoft next version.
2. Community of vNext, if there are many developers going to be familiar with it soon.

**Comment by rmarinho** [comment]
IMHO i think is definitely a good bet .. even with sacrifice in the next 6 months.. RC1 is out in 2 months and 1.0 on 2016 Q1 https://github.com/aspnet/Home/wiki/Roadmap

In terms of developers i think so as they will eventually stop support efforts in the old versions.. new features will come first to asp.net new versions.
Also you know can target new developers that normally worked with others tools but know since is light and cross platform will start to look at asp.net. 

 EF  7 looks similar in terms of rebase date - https://github.com/aspnet/EntityFramework/wiki/Roadmap

**Comment by kenyeung128** [comment]
it's definitely something we would consider at some point in the future because of the cross platform feature, will keep an eye on that. Right now, we are also try to stabilize all the features in the marketplace framework as well.
