### ISSUE TITLE
application gets error when clicking headers of listings in list view

### ISSUE THREAD

**Issue by cao1998wang** [beyourmarket/beyourmarket#23]
below is the error message:

Server Error in '/' Application.

The resource cannot be found.

Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable.  Please review the following URL and make sure that it is spelled correctly. 

Requested URL: /en

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.34248

**Comment by kenyeung128** [comment]
it looks like an environment issue, where do you run it and if you installed latest .net framework?

**Comment by cao1998wang** [comment]
It runs in VS 2013 in windows 8.1.  I will try installing latest .net
framework. Thanks!

**Comment by kenyeung128** [comment]
Hi, I got wrong on what you mean, you are right, there is a bug when clicking the listing, it's fixed now in the latest version :)
