### ISSUE TITLE
More than one image when add new listing

### ISSUE THREAD

**Issue by ukurt** [beyourmarket/beyourmarket#25]
Hello,

When I am adding a new listing, ı am trying to add one more image to this listing but second image is crushing the first image. How can I add more than one image to a listing ?

Thanks.

Unal

**Comment by kenyeung128** [comment]
Hi Unal, have you found the issue?

**Comment by ukurt** [comment]
Yes, actually there is no issue, I did not select more than one image when pop up opened :)

But Can I ask another question ? How can I fix all image size ? When I add an image and come to the listing page, list box longer than other. How can I fix this problem ?

Thanks.
