### ISSUE TITLE
updates on azure

### ISSUE THREAD

**Issue by selombanybah** [beyourmarket/beyourmarket#29]
Whenever I update the app and I publish to azure, settings like logo, header image are back to default.
Any idea what may cause that?

**Comment by kenyeung128** [comment]
I guess the images are not uploaded to azure?

**Comment by selombanybah** [comment]
So you mean, everytime i update the app, the images are deleted? I use the
admin panel to update logo and header.

**Comment by selombanybah** [comment]
I will try it again today but before update i will backup db and use ftp to
download the files from azure so i can track exactly whats going on.
Thanks

**Comment by selombanybah** [comment]
Ok the issue is that the file connectionstring.config is empty when published to azure. So I configure it manually through ftp.
If I want to use the preview (last step to publish) in visual studio so I can uncheck the connectionstring.config, it gives me this error

Expecting attribute 'kind'.
\BeYourMarket.Web\obj\Release\Package\FilePreviewParameter.xml

What do you guys think?

**Comment by kenyeung128** [comment]
if connectionstring.config is not copied, might be you can configure the publish function again. For initial connectionstring.config, it shall be empty, with lines as below.

<connectionStrings>
</connectionStrings>

**Comment by selombanybah** [comment]
Thank you. I'm fine now.
