### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by net4u** [beyourmarket/beyourmarket#3]
I suggest because if you are in application as admin, already exists the dropdown menu of the user, to delete the Dashboard and Admin Panel entries from the left slide-in panel. It can be confusing somehow.
Also is not clear for me what is the benefit for showing the administrative pages in new window/tab?
I will try this changes tomorrow and I will provide a link to take a look and evaluate.

I found to be a little confusing the way to be displayed the administrative sections (also are named identically but seems to be different, e.g. we have dashboard that displays statistics, but also dashboard from popup menu that displays profile related info's such as orders, transactions etc.)

**Comment by carolyau12** [comment]
Thanks. We will take that into consideration.

**Comment by beyourmarket** [comment]
thanks. we will take that into consideration.
