### ISSUE TITLE
The virtual path '/' maps to another application, which is not allowed.

### ISSUE THREAD

**Issue by mis0033** [beyourmarket/beyourmarket#32]
hello everybody,

when I uploaded my site to Godaddy shared hosting, I got this error, please help , any suggestions ? the web site is http://www.global-energyco.com/en

---

Server Error in '/globalenergy' Application.

The virtual path '/' maps to another application, which is not allowed.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.ArgumentException: The virtual path '/' maps to another application, which is not allowed.

Source Error:

**Comment by mis0033** [comment]
notice that I am using beyourmarket CMS

**Comment by kenyeung128** [comment]
Hi, did you change the root path in visual studio solution? you might try the solution below.

http://stackoverflow.com/questions/19277350/asp-net-virtual-path-maps-to-another-application-which-is-not-allowed

**Comment by mis0033** [comment]
Many thanks for your reply but how can I change the virtual path in BeYourMarket.Web , it's web application project not web site and I'm using MS VS 2015

**Comment by kenyeung128** [comment]
This can be found by right click the project and opening the properties dialog: Solution->Properties->Virtual Path-> Change to "/"

**Comment by mis0033** [comment]
the settings that you are talking about are not exist , please check this screenshot from my machine, again I'm using a web application not web site , it's the same source project that i installed from BeYourMarket web site

https://www.dropbox.com/s/5kh8eu0auhhiqpj/beyourmarket.png?dl=0

**Comment by mis0033** [comment]
any replies please , sorry for bothering you , but it's more than urgent

**Comment by mis0033** [comment]
Hello Ken Yeung, any advise please

**Comment by kenyeung128** [comment]
hi, your settings looks correct, it's root as i see. Also did you publish as File System? I think it's related to GoDaddy setting, did you try to ask them?
