### ISSUE TITLE
Too slow to load on server

### ISSUE THREAD

**Issue by silverup** [beyourmarket/beyourmarket#39]
Hello @kenyeung128  Thank you for creating this, i'm studying it, modifying it  and looks great, I'm trying to use it on a go daddy hosting , but it seems really slow to launch the app , like sometime I have to wait a minute, have you experience the same issue? if so what is the steps to deploy this application properly into hosting?

thank you any help is appreciated it

**Comment by egouin** [comment]
Same problem on same web provider.
i treid a "keep alive" loop but didnt work long

**Comment by silverup** [comment]
@egouin , I recommend you try a different hosting provider. it makes a world of difference

**Comment by kenyeung128** [comment]
@egouin , probably you need to update the application pool setting, otherwise, the AppPool will get recycle periodically.

**Comment by abd5ge3** [comment]
@silverup Did you ever figure this out?
