### ISSUE TITLE
Deploy to azure

### ISSUE THREAD

**Issue by sebvst** [beyourmarket/beyourmarket#54]
Hello, did anyone of you manage to deploy it to Azure? When I deploy it I can acess the installation page, but then it won't create any database tables. 

Did you make similar experiences? And did you maybe solve the problem?

Locally I can connect to SQL Server.

**Comment by sameerdube9** [comment]
I did it
I have manually uploaded db to Azure after setting up locally

**Comment by sebvst** [comment]
Thank you for that information. I found out what my problem was:

Azure SQL had not enough performance. I therefore set up a virtual machine on Azure with MS SQL Server 2014 express. Then everything worked correctly.
