### ISSUE TITLE
Question about payment process

### ISSUE THREAD

**Issue by net4u** [beyourmarket/beyourmarket#6]
Hi,
Please briefly explain the payment process as business aspect. I don't understand how it works.
So we have an service provider that sell something at an given amount, a buyer and you in the middle.
The buyer pay the amount, that is processed by stripe and the money goes to you, or directly to the service provider?
I am not quite understanding how it works because is different from the typical e-commerce where only the shop owner must be registered with payment provider..
In any cases, I may suppose that every service provider must somehow be registered with Stripe?
Also in what concerns the taxes due to the income, how is the deal? 
Ok, here are many variables depending of national fiscal regulations, but at least here in E.U. I suppose that we have similar principles; e.g. here in Romania we have two kinds of taxation level, there are microenterprises that due 3% of income or regular enterprises that due 16% of profit. The first case is convenient if you don't have big spending, so is not appropriate if you have an income of let say 100 euros and you have to pay at your turn 90 euros to service provider registered in application. The second case is convenient in this scenario when you can have big spending. Also is the aspect of VAT: for example here we have two kind of enterprises: VAT registered that must settle the VAT with state, and the exempt enterprises that pay VAT for the goods and services that they buy, but don't settle nothing with the state. This aspects are important on my advice in terms of fiscalization and invoicing.

**Comment by beyourmarket** [comment]
Yes, it's a good point. Indeed, we are working on a plugin architecture, where you could write you own payment method. it shall be released some time in July. We will provide documentation when it's get released.

**Comment by beyourmarket** [comment]
plan to release in July/August this year.

**Comment by net4u** [comment]
Here I think also at an "offline" payment (can mean pay by card at the siege, by cash, by courier, or other not-online means)

**Comment by do-n-khanh** [comment]
@net4u can you make cash on delivery plugin payment? If you can, could you please share it?

**Comment by hitaspdotnet** [comment]
@do-n-khanh @net4u  are you make cash on delivery plugin? please share it if is possible
