### ISSUE TITLE
Map is vanish

### ISSUE THREAD

**Issue by net4u** [beyourmarket/beyourmarket#7]
Hi, when in detail view of an listing item, google map is not visible (it was yesterday). However in edit mode is still there
L.E.
I found that (probably because of EF migration) lat / long for entries is lost in the DB. But even if I edit the listing, the pair of lat / long is not saved.

**Comment by beyourmarket** [comment]
can you give me example? seems it's working.

**Comment by net4u** [comment]
Hi,

I write above in L.E. that I found a probable cause: for some reason (possible inconsistent migration) when I add/edit a listing lat/long are not saved in DB. For this reason, map is not visible.

**Comment by beyourmarket** [comment]
yes, that would be the possible cause.

**Comment by net4u** [comment]
So I downloaded today the latest commit, I dropped the existing DB, and I have the same issue: when editing an existing listing, when change it's address, then lat/long disappear from db record. It is the same when I add a new listing, but it keeps the info when I edit something else but leave address untouched. So since I produce a new installation, it seems to me that something is broke in Controller.

**Comment by beyourmarket** [comment]
ok, i will test that later.

**Comment by beyourmarket** [comment]
i tested that by adding new listing with location, the address and map shows correctly. could you try the latest version?

**Comment by net4u** [comment]
Still have the map issue when add or edit an existing listing: the address is initially show on map, but not saved in DB. I am on version downloaded today (DB dropped and recreated). Any hint?
