### ISSUE TITLE
Suggestion #5

### ISSUE THREAD

**Issue by selombanybah** [beyourmarket/beyourmarket#9]
It will be good to have a bidding system. What do you guys think?

**Comment by beyourmarket** [comment]
Hi, could you explain more about the bidding system? like an example. thanks.

**Comment by selombanybah** [comment]
Well, the idea is to allow users to post projects and let the service providers bet for it.
I think this will make the platform more interesting for the service providers.
As an example, you can look at freelancer.com

**Comment by beyourmarket** [comment]
right, that's a good idea. it means the user could request a task, where service providers could bid for it. do you have a concrete project to work on? might be we could have a closer look of your requirement.

**Comment by beyourmarket** [comment]
hi, the latest version now supports different listing types, which means you could add a type "Request", and user could make a request to post project where other users could offer services.

**Comment by selombanybah** [comment]
Thank you. I will look into it.
